### ISSUE TITLE
Can't break any blocks

### ISSUE THREAD

**Issue by capuano1** [pmme/Boost#1] opened 2020-04-05 03:18 UTC
I just installed the last version of this plugin (for now 1.6.0) and when I enter the server, it makes me spawn underground and also makes me unable to break or place any blocks. I'm using Spigot 1.15.2-R0.1.

**Comment by pmme** [comment] 2020-04-05 03:26
Edit spawn location for main lobby in config.yml. That'll fix the
underground.
Use "/boost build" to be in build mode and "/boost nobuild" to be in play
mode.

**Comment by capuano1** [comment] 2020-04-05 03:31
So your plugin basically messes with my Essentialsx spawn? Because when I enter my server without your plugin, I just enter normally. I didn't even tested it, just installed and when I enter the server, it makes me spawn undergroud and makes me unable to place or break blocks.

**Comment by pmme** [comment] 2020-04-05 03:46
It hasn't changed your essentials at all. However, since it's a minigame with arenas it must manage player locations. 
When a player logs into the server it tp's them to the main lobby spawn (as specified in config.yml) so that they don't re-appear in an arena if they happened to have logged off mid-game. 

In the "world" where you run the minigame you cannot be also playing other game modes. 
If you want a mix of both (minigame + other game modes), you will need to use multiverse or similar to have a server with multiple worlds. The world where Boost is active is dedicated to Boost. Out of necessity, to run a minigame, it will take control of various normal Minecraft game aspects such as block breaking and spawn location.

If you will be using a multi-world setup so that you can have other game modes, you can change the "boost_worlds:" to have the name of the world or worlds in which you will have Boost active. You should also set "main_lobby" where you want players to spawn upon joining.

**Comment by capuano1** [comment] 2020-04-05 04:02
Ohh, now I understand. I'm not used to minigames that really need their own world, and that have this building mode enabled and disabled. Sorry to bother you, and thanks for your help! Now it works, I've just created a world specifically for Boost!

**Comment by pmme** [comment] 2020-04-05 04:07
All good. Glad to hear you're getting there. Pm server ip through spigotmc if you'd like some tips making arenas etc.

**Comment by capuano1** [comment] 2020-04-05 04:09
Now the problem is another: Every time that I change worlds (entering portals to another Multiverse world or just warping to another multiverse world) I receive on the chat "[Boost] You are not in a Boost game.". If I just try to warp to another place on the same world, I don't receive the message, is only when it changes from any of the worlds to another.

**Comment by pmme** [comment] 2020-04-05 04:12
Hmmm will need to look at that but can't right now. Will update you as soon as I can though.

**Comment by pmme** [comment] 2020-04-05 05:37
Hi @capuano1 the bug causing that message to appear is fixed now. It was down to inadequate testing on my part sorry. Unfortunate you've had a rocky start, but that should be good now.

Two things to note for fair warning (that I've only just realised):
* Boost commands (like /boost join) need to check worlds.
* There's no inventory protection for multi-world implementation currently - eek!

Boost was initially written as an own-server minigame, i.e. a separate server of its own in a Bungee network. It clears inventory and gives items as part of the game. For proper multi-world support, where your other worlds could be running survival, that will wreak havoc on players' inventories.

By all means try out the game but, if you're after multi-world support then I've realized that's not properly available just yet.

**Comment by capuano1** [comment] 2020-04-05 06:38
Oh well, maybe I can make this work with multi-world using some commands and plugins, I'll try, and there's just a little something: It is indeed working, it doesn't give me that message anymore, but every time I change worlds it does give me a error on the console. Now, I haven't created any arenas of your minigame yet because it's 3:38AM where I live, but I don't think this error will give me any problems while playing Boost, it's just that makes the console look very unclean, so it's a minor bug. But, here is the link to a Pastebin of the error code (since it's a little big, I didn't want to make this comment huge because of it): https://pastebin.com/QX36ueQ5
It happens if I try to teleport with EssentialsX and also with Ancient Gates (both errors are on that pastebin)

**Comment by pmme** [comment] 2020-04-05 08:15
Thanks for the report. I'm not getting an error using MultiVerse to TP between worlds. I will try EssentialsX warp when I next get the chance.

If I can't reproduce it I will offer to send you a special build with some run-time debugging logging to find the thing that's coming up null in the event.

I'll definitely get it sorted though. I certainly don't want it spamming anyone's console.

**Comment by pmme** [comment] 2020-04-05 20:50
I cannot reproduce the error using Essentials /warp or /spawn.
If you have time to help further, please send me a private message on spigotmc and I'll send you a build with debugging output that should reveal what is coming up null when it's on your server.

**Comment by pmme** [comment] 2020-04-19 06:23
Thanks for your help resolving the issues.
That's all available in version 1.6.2 along with additions.

**Closed as completed by pmme** 2020-04-19 06:23 UTC
